#!/bin/bash

PORT1=1
PORT2=2
PRINTER=3

VDISK=vdisk
CPU=2
CD=../disk/MTXinstallCD.iso
RAM=520 #MB

qemu-system-i386 -hda $VDISK -m ${RAM}M -smp $CPU -serial /dev/pts/$PORT1 -serial /dev/pts/$PORT2 -parallel /dev/pts/$PRINTER -localtime -cdrom $CD  #-boot d
