#!/bin/bash

VDISK=vdisk
CPU=2
CD=../disk/MTXinstallCD.iso
RAM=520 #MB

qemu-system-i386 -hda $VDISK -m ${RAM}M -smp $CPU -serial /dev/pts/$1 -serial /dev/pts/$2 -parallel /dev/pts/$3 -localtime -cdrom $CD  #-boot d
