#!/bin/bash

if [ $# \< 1 ]; then echo Usage: mku filename; exit; fi

# default partiton = 1
PARTITION=1
if [ $# \> 1 ]; then PARTITION=$2; fi

VDISK=jj2_vdisk
SECTOR=$(./ptable $VDISK $PARTITION)
OFFSET=$(expr $SECTOR \* 512)

echo partition=$PARTITION sector=$SECTOR offset=$OFFSET
#read dummy

sudo mount -o loop,offset=$OFFSET $VDISK /mnt

echo compiling $1.c .....
as86 -o u.o u.s
bcc -c -ansi $1.c -o $1.o 
bcc -c -ansi ucode.c -o ucode.o 
bcc -c -ansi util.c -o util.o 

echo linking .......
ld86 u.o $1.o ucode.o util.o mtxlib /usr/lib/bcc/libc.a -o $1 2> /dev/null 

echo copying $1 into $VDISK/bin/$1

sudo cp -av $1 /mnt/bin/$1
sudo umount /mnt

echo done $1
